name: Sanity
on:
  schedule:
    - cron: '13 13 8 * *'
  push:
    branches:
      - '*'

jobs:
  compile:
    name: Compilation
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Tools
        run: |
          sudo apt-get install -y gcc-avr avr-libc
          pip install ruamel.yaml

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Make
        run: |
          make
